# -*- coding: utf-8 -*-
"""GEE_TreeMap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zT0qv-vHnzRUn8Pqo_7kMsfdGG6kmZY5
"""

from google.colab import drive
drive.mount('/content/drive')
import os
directory_path = '/content/drive/MyDrive/Newwave'
files = os.listdir(directory_path)
print(files)

# Import necessary libraries
import ee
import geemap
import folium
from google.colab import drive

# Authenticate and initialize Earth Engine
ee.Authenticate()
ee.Initialize(project='nlcd-project')

# Load the image collection
collection = ee.ImageCollection('USFS/GTAC/TreeMap/v2016')

# Mosaic the collection to combine all images into a single image
dataset = collection.mosaic()

# Select the desired layers
canopy_cover = dataset.select('CANOPYPCT')
live_trees_per_acre = dataset.select('TPA_LIVE')
stand_height = dataset.select('STANDHT')

# Combine the selected layers into a single image
selected_layers = dataset.select(['CANOPYPCT', 'TPA_LIVE', 'STANDHT'])

# Define a point of interest (Longitude, Latitude)
point = ee.Geometry.Point(-85, 35.0)  # Replace 37.0 with the desired latitude

# Define an area of interest (buffer around the point)
area_of_interest = point.buffer(10000)  # Buffer in meters (e.g., 10 km radius)

# Clip the combined image to the area of interest
layers_clipped = selected_layers.clip(area_of_interest)

# Get statistics for the selected layers in the area of interest
stats = layers_clipped.reduceRegion(
    reducer=ee.Reducer.mean(),
    geometry=area_of_interest,
    scale=30  # Scale in meters (resolution of the dataset)
)

# Print the result
print('Layer statistics:', stats.getInfo())

# Export the clipped image to Google Drive (Optional)
task = ee.batch.Export.image.toDrive(
    image=layers_clipped,
    description='Selected_Layers_Export',
    folder='GEE_Exports',  # Google Drive folder name
    fileNamePrefix='selected_layers',
    scale=30,  # Scale in meters
    region=area_of_interest.bounds().getInfo()['coordinates'],
    crs='EPSG:4326'
)

task.start()
print('Export task started. Check your Google Drive.')

